import Head from "next/head"
import { FC } from "react"

const HeadProvider: FC = () => (
  <Head>
    <title>{"Bruno's Garden"}</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
)

export default HeadProvider
